"""gspread-backed implementation of calbum.sheets.SheetBackend. The only
place gspread itself gets imported — see PLAN.md "The module boundary that
matters", the same isolation pattern as spotify/ and discogs/."""

from __future__ import annotations

import json

import gspread
from gspread.utils import ValueInputOption, rowcol_to_a1


class GspreadSheetBackend:
    def __init__(self, sa_json: str, sheet_id: str):
        credentials = json.loads(sa_json)
        client = gspread.service_account_from_dict(credentials)
        self._spreadsheet = client.open_by_key(sheet_id)
        self._service_account_email = credentials["client_email"]

    def replace_tab(self, title: str, rows: list[list[object]]) -> None:
        """Delete-if-present, create fresh, write, freeze header, protect.
        Deleting and recreating (rather than clearing in place) is what
        makes "delete a tab by hand, next run rebuilds it" — the stage's own
        done-when — true for free, and sidesteps ever needing to edit
        through a protection left over from a prior run: that protection is
        deleted along with the old tab before the new one is protected."""
        try:
            self._spreadsheet.del_worksheet(self._spreadsheet.worksheet(title))
        except gspread.exceptions.WorksheetNotFound:
            pass

        num_rows = max(len(rows), 1)
        num_cols = max((len(row) for row in rows), default=1)
        worksheet = self._spreadsheet.add_worksheet(title=title, rows=num_rows, cols=num_cols)

        if rows:
            # USER_ENTERED, not RAW: RAW would write "=HYPERLINK(...)" as a
            # literal string instead of parsing it as a formula.
            worksheet.update(rows, value_input_option=ValueInputOption.user_entered)

        # Formatting before protection, deliberately: add_protected_range
        # restricts further edits to whatever account/permission mechanism
        # is set up for that range (the "can't remove yourself as an editor"
        # class of bug fixed earlier this session), so any formatting must
        # land first — doing it after risks rediscovering that same class of
        # failure from the other side.
        #
        # The header format is its own full textFormat object, not a
        # bold-only follow-up call — confirmed live that the Sheets API
        # replaces a cell's entire textFormat per format() call rather than
        # merging fields, so a bold-only call after the base font call wiped
        # out fontFamily/fontSize on the header row.
        last_cell = rowcol_to_a1(num_rows, num_cols)
        base_font = {"fontFamily": "Roboto", "fontSize": 10}
        worksheet.format(f"A1:{last_cell}", {"textFormat": base_font})
        worksheet.format(f"A1:{rowcol_to_a1(1, num_cols)}", {"textFormat": {**base_font, "bold": True}})
        worksheet.columns_auto_resize(0, num_cols)

        worksheet.freeze(rows=1)
        worksheet.add_protected_range(
            f"A1:{last_cell}",
            # gspread's own docstring: "editor_users_emails must at least
            # contain the e-mail address used to open that SpreadSheet."
            # Confirmed live: omitting this (even with
            # requesting_user_can_edit=True alone) fails with "You can't
            # remove yourself as an editor" — the empty list this defaults
            # to is sent as an explicit "no editors", not "auto-add owner"
            # as the docstring's first paragraph implies.
            editor_users_emails=[self._service_account_email],
            description="Generated by calbum — hand edits are overwritten every run.",
            requesting_user_can_edit=True,
        )
